### ISSUE TITLE
Cannot Load ImageFonts

### ISSUE THREAD

**Issue by surpol** [Logeswaran123/MrPose#1]
INPUT: python3 mrpose.py --video /Users/surya/desktop/pexels-yaroslav-shuraev-8472764-3840x2160-25fps.mp4 --exercise pushup

Output: 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/Users/surya/Desktop/MrPose/mrpose.py", line 16, in <module>
    pose.estimate_exercise()
  File "/Users/surya/Desktop/MrPose/utils/exercise_utils.py", line 17, in estimate_exercise
    pose_estimator = pose_estimator(self.video_reader)
  File "/Users/surya/Desktop/MrPose/utils/pose_utils/pose.py", line 277, in __init__
    super().__init__(video_reader)
  File "/Users/surya/Desktop/MrPose/utils/pose_utils/pose.py", line 31, in __init__
    self.draw = Draw(self.width, self.height)
  File "/Users/surya/Desktop/MrPose/utils/drawing_utils.py", line 15, in __init__
    self.font = ImageFont.truetype('../data/fonts/arial.ttf', self.height//24, encoding="unic")
  File "/Users/surya/Library/Python/3.9/lib/python/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/Users/surya/Library/Python/3.9/lib/python/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Users/surya/Library/Python/3.9/lib/python/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by speed8928** [comment]
Go into the drawing_utils.py and change the line 15 to 

self.font = ImageFont.load_default()
